### ISSUE TITLE
Стилизовать шрифты Clear Sans.

### ISSUE THREAD

**Issue by YLeight** [JIoJIaJIu/goldpoisk_frontend#193]
Issue #171 - Стилизовать шрифты единым образом
Пример:

``` css
@font-face {
        font-family: 'my-font-family';
        src: url('my-font-filename.eot');
        src: url('my-font-filename.eot?#iefix') format('embedded-opentype'),
        url('my-font-filename.svg#my-font-family') format('svg'),
        url('my-font-filename.woff') format('woff'),
        url('my-font-filename.ttf') format('truetype');
        font-weight: normal;
        font-style: normal;
    }
```
